// <auto-generated />
using MZWalks.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MZWalks.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250811152206_Add seeded data")]
    partial class Addseededdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MZWalks.Api.Models.Domain.Difficulty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = "01HZX0J5ZWGFA1D9S3H4HMGWVD",
                            Name = "Easy"
                        },
                        new
                        {
                            Id = "01HZX0J5ZX9Y9S9TCS59R3KH9J",
                            Name = "Medium"
                        },
                        new
                        {
                            Id = "01HZX0J60AZK3D9R9YFMC2DJMD",
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("MZWalks.Api.Models.Domain.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MZWalks.Api.Models.Domain.Region", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = "01HZX0J60B8J1A8RPX1M0XQJ3N",
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageURL = "https://images.nzregions.com/auckland.jpg"
                        },
                        new
                        {
                            Id = "01HZX0J60C1J1A8RPX2N1YQJ3P",
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageURL = "https://images.nzregions.com/wellington.jpg"
                        },
                        new
                        {
                            Id = "01HZX0J60D1J1A8RPX3Z2ZQJ3Q",
                            Code = "CAN",
                            Name = "Canterbury",
                            RegionImageURL = "https://images.nzregions.com/canterbury.jpg"
                        },
                        new
                        {
                            Id = "01HZX0J60E1J1A8RPX4P3AQJ3R",
                            Code = "STL",
                            Name = "Southland",
                            RegionImageURL = "https://images.nzregions.com/southland.jpg"
                        },
                        new
                        {
                            Id = "01HZX0J60F1J1A8RPX5D4BQJ3S",
                            Code = "OTA",
                            Name = "Otago",
                            RegionImageURL = "https://images.nzregions.com/otago.jpg"
                        });
                });

            modelBuilder.Entity("MZWalks.Api.Models.Domain.Walk", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(26)");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("WalkImageURl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("MZWalks.Api.Models.Domain.Walk", b =>
                {
                    b.HasOne("MZWalks.Api.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZWalks.Api.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
